package com.mycompany.loginproyect.formularios;
import com.mycompany.loginproyect.clases.Usuario;

public class FrmDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDashboard.class.getName());
    
    private Usuario usuario;

    public FrmDashboard(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;

        LblNombreUsuario.setText(usuario.getNombre() + " " + usuario.getApellido());
        LblCorreUsuario.setText(usuario.getEmail());
        LblRoluUsuario.setText(usuario.getRol());
    }

    public FrmDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        LblBienvenido = new javax.swing.JLabel();
        LblUsuarioIcon = new javax.swing.JLabel();
        LblNombreUsuario = new javax.swing.JLabel();
        LblCorreUsuario = new javax.swing.JLabel();
        LblRoluUsuario = new javax.swing.JLabel();
        BtnPagina = new javax.swing.JButton();
        BtnFacebook = new javax.swing.JButton();
        BtnLinkedin = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setPreferredSize(new java.awt.Dimension(1129, 697));

        LblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        LblBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        LblBienvenido.setText("BIENVENIDO AL SISTEMA");

        LblUsuarioIcon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        LblUsuarioIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/loginproyect/imagenes/userinfo.png"))); // NOI18N

        LblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LblCorreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblCorreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LblCorreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LblRoluUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblRoluUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LblRoluUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BtnPagina.setBackground(new java.awt.Color(255, 255, 255));
        BtnPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/loginproyect/imagenes/website.png"))); // NOI18N
        BtnPagina.setBorder(null);
        BtnPagina.setBorderPainted(false);
        BtnPagina.setPreferredSize(new java.awt.Dimension(46, 46));

        BtnFacebook.setBackground(new java.awt.Color(255, 255, 255));
        BtnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/loginproyect/imagenes/face.png"))); // NOI18N
        BtnFacebook.setBorder(null);
        BtnFacebook.setBorderPainted(false);
        BtnFacebook.setPreferredSize(new java.awt.Dimension(46, 46));

        BtnLinkedin.setBackground(new java.awt.Color(255, 255, 255));
        BtnLinkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/loginproyect/imagenes/linkedin.png"))); // NOI18N
        BtnLinkedin.setBorder(null);
        BtnLinkedin.setBorderPainted(false);
        BtnLinkedin.setPreferredSize(new java.awt.Dimension(46, 46));

        BtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/loginproyect/imagenes/logout.png"))); // NOI18N
        BtnSalir.setBorder(null);
        BtnSalir.setBorderPainted(false);
        BtnSalir.setPreferredSize(new java.awt.Dimension(46, 46));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addComponent(LblBienvenido)
                        .addGap(424, 424, 424))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addComponent(LblUsuarioIcon)
                        .addGap(522, 522, 522))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LblCorreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DashboardLayout.createSequentialGroup()
                                .addComponent(BtnFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LblRoluUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(485, 485, 485))))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(LblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUsuarioIcon)
                .addGap(18, 18, 18)
                .addComponent(LblNombreUsuario)
                .addGap(21, 21, 21)
                .addComponent(LblRoluUsuario)
                .addGap(18, 18, 18)
                .addComponent(LblCorreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnFacebook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
      FrmLogin login = new FrmLogin();
      login.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFacebook;
    private javax.swing.JButton BtnLinkedin;
    private javax.swing.JButton BtnPagina;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel LblBienvenido;
    private javax.swing.JLabel LblCorreUsuario;
    private javax.swing.JLabel LblNombreUsuario;
    private javax.swing.JLabel LblRoluUsuario;
    private javax.swing.JLabel LblUsuarioIcon;
    // End of variables declaration//GEN-END:variables
}
